In [2]:
import pandas as pd
df = pd.read_csv('./Demographic Data Analyzer/adult.data.csv')
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [3]:
# How many people of each race are represented in this dataset?
# This should be a Pandas series with race names as the index labels. (race column)

In [10]:
race_count = df.race.value_counts()
race_count

race
White                 27816
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: count, dtype: int64

In [ ]:
# What is the average age of men?

In [19]:
avg_men_age = df[df['sex'] == 'Male'].age.mean()
avg_men_age

np.float64(39.43354749885268)

In [ ]:
# What is the percentage of people who have a Bachelor's degree?

In [29]:
total_people = df.shape[0]
bachelor_people = len(df[df['education'] == 'Bachelors'])
percentage_bachelors = round((bachelor_people/total_people) * 100, 1)
percentage_bachelors

16.4

In [30]:
#What percentage of people with advanced education
#(Bachelors, Masters, or Doctorate) make more than 50K?

In [41]:
higher_degrees = ['Bachelors','Masters','Doctorate']
higher_education = df[df['education'].isin(higher_degrees)]
educated_withmorethan_50K = higher_education[higher_education['salary'] == '>50K']
percentage_higher_degrees_morethan_50k = round((len(educated_withmorethan_50K)/len(higher_education)) * 100, 1)
percentage_higher_degrees_morethan_50k

46.5

In [ ]:
# What percentage of people without advanced education make more than 50K?

In [44]:
lower_education = df[~df['education'].isin(higher_degrees)]
noeducated_withmorethan_50K = lower_education[lower_education['salary'] == '>50K']
percentage_no_degrees_morethan_50K = round((len(noeducated_withmorethan_50K)/len(lower_education)) * 100, 1)
percentage_no_degrees_morethan_50K

17.4

In [ ]:
# What is the minimum number of hours a person works per week?

In [50]:
min_hours = df['hours-per-week'].min()
min_hours

1

In [49]:
# What percentage of the people who work the minimum number of hours per week have
# a salary of more than 50K?

In [56]:
count_how_many_work_1hour = df[df['hours-per-week'] == min_hours]
hour_and_morethan_50K = count_how_many_work_1hour[count_how_many_work_1hour['salary'] == '>50K']
percentage_hour_and_morethan_50K = round((len(hour_and_morethan_50K)/len(count_how_many_work_1hour)) * 100, 1)
percentage_hour_and_morethan_50K

10.0

In [55]:
# What country has the highest percentage of people that earn >50K and what is that
# percentage?

Object `percentage` not found.

In [80]:
people_per_country = df['native-country'].value_counts()
rich_people_per_country = df[df['salary'] == '>50K']['native-country'].value_counts()
country_percentages = (rich_people_per_country / people_per_country) * 100
highest_earning_country = country_percentages.idxmax()
highest_earning_country_percentage = round(country_percentages.max(), 1)
print(f"The country with the highest percentage of people earn >50K is {highest_earning_country} with {highest_earning_country_percentage}%")

The country with the highest percentage of people earn >50K is Iran with 41.9%

In [ ]:
# Identify the most popular occupation for those who earn >50K in India.

In [83]:
rich_indians = df[(df['native-country'] == 'India') & (df['salary'] == '>50K')]
occupation_counts = rich_indians['occupation'].value_counts()
top_IN_occupation = occupation_counts.idxmax()
print(f"The most popular occupation for high earners in India is: {top_IN_occupation}")

The most popular occupation for high earners in India is: Prof-specialty